name: optimusprime
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  cached_network_image: ^3.4.1
  crypto: ^3.0.6
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  go_router: ^14.6.2
  http: ^1.3.0
  intl: ^0.19.0
  rxdart: ^0.28.0
  uuid: ^4.5.1
  webview_flutter: ^4.10.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/
